export const CLICK_ICON = "CLICK_ICON";
export const CLICK_APPLICATION_ICON = "CLICK_APPLICATION_ICON";
export const CLOSE_ICON_WINDOW = "CLOSE_ICON_WINDOW";
export const CLOSE_APPLICATION_WINDOW = "CLOSE_APPLICATION_WINDOW";

export const CLICK_START_MENU_ITEM = "CLICK_START_MENU_ITEM";
export const CLOSE_START_MENU_WINDOW = "CLOSE_START_MENU_WINDOW";
