export const CLICK_ICON = "CLICK_ICON";
export const CLICK_APPLICATION_ICON = "CLICK_APPLICATION_ICON";
export const CLOSE_ICON_WINDOW = "CLOSE_ICON_WINDOW";
export const CLOSE_APPLICATION_WINDOW = "CLOSE_APPLICATION_WINDOW";
